from enum import IntEnum

class TrialType(IntEnum):
    COMPLETELY_RANDOMIZED = 1
    COMPLETELY_RANDOMIZED_IN_BLOCKS = 2
    BERNOULLI_RANDOMIZED = 3
    BERNOULLI_RANDOMIZED_IN_BLOCKS = 4
    NON_RANDOMIZED = 5
    POTENTIAL_OUTCOMES = 6
